---
name: Stale

on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - name: Run stale
        uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-close: -1
          stale-issue-label: status/stale
          stale-pr-label: status/stale
          exempt-issue-labels: status/triage,status/in-progress,help/beginner,help/intermediate,help/advanced
          exempt-pr-labels: status/triage,review/pending
          remove-stale-when-updated: true
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity and will be closed in 7 days.
            If you still need help, please leave a comment and it will have the stale label removed.
          stale-pr-message: >
            This pull request has been automatically marked as stale due to inactivity.
            If you still wish to work on this pull request, please leave a comment and it will have the stale label removed.
